{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-chassis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fastapi-chassis.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (eq (.Values.database.backend | default "postgres") "postgres") .Values.database.postgres.password }}
  APP_DATABASE_POSTGRES_PASSWORD: {{ .Values.database.postgres.password | quote }}
  {{- end }}
  {{- if and (eq (.Values.database.backend | default "postgres") "custom") .Values.database.url }}
  APP_DATABASE_URL: {{ .Values.database.url | quote }}
  APP_ALEMBIC_DATABASE_URL: {{ .Values.database.alembicUrl | default .Values.database.url | quote }}
  {{- end }}
  {{- if .Values.redis.password }}
  APP_REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  {{- end }}
  {{- if and .Values.auth.enabled .Values.auth.jwtSecret }}
  APP_AUTH_JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  {{- end }}
  {{- if and .Values.auth.enabled .Values.auth.jwtPublicKey }}
  APP_AUTH_JWT_PUBLIC_KEY: {{ .Values.auth.jwtPublicKey | quote }}
  {{- end }}
  {{- with .Values.extraSecretEnv }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
