apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-chassis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fastapi-chassis.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fastapi-chassis.selectorLabels" . | nindent 4 }}
